### ISSUE TITLE
Default logstash file is not available under the templates  

### ISSUE THREAD

**Issue by gokhan27** [rskeskin/ansible-role-logstash#1]
role gets error on this line: https://github.com/rskeskin/ansible-role-logstash/blob/master/tasks/logstash_post_install.yml#L29 . Because there is no default logstash file.

**Comment by rskeskin** [comment]
https://github.com/rskeskin/ansible-role-logstash/commit/3fa599a7d150ead27f62c778e0780a9ab12d6ed0
Fixed
